### ISSUE TITLE
Update .d.ts to allow the needle to be B rather than A.

### ISSUE THREAD

**Issue by rnemec** [darkskyapp/binary-search#13] opened 2017-05-06 01:56 UTC
Would you please update the declaration to reflect that the needle may be different type from the haystack array. And the comparator should follow.
Thank you

**Comment by ironwallaby** [comment] 2017-05-08 20:07
@rnemec We don't use TypeScript here internally, so the TypeScript bindings are community-maintained! If either you or @darcyparker (who wrote the original binding) could issue a PR, it would be appreciated!

**Comment by darcyparker** [comment] 2017-05-08 20:28
So I can understand it better, when would the `needle` be a different type than the `haystack`?  And if there is a use case, I assume the `comparator` implies there would be a mapping function from the needle type to the haystack type built into it?  If so, it seems like it would be wise to explicitly define and use this mapping func to ensure you didn't make a mistake in the map?

**Comment by darcyparker** [comment] 2017-05-08 21:44
Thanks for clarifying.  You're right that the typescript definition could be defined with separate types for the `needle`,  `haystack` and `comparator`,  but as a TS developer you are loosing the type definition of the fact that the `number` in your example is a property in the haystack's object type.  This seems a bit dangerous.  A mapping function would help with clarity and you'd be protected from possible errors in your  `comparator` implementation.

On the other hand, I can appreciate the possible performance benefit of not having a mapping function and essentially in-lining it into your `comparator` implementation.

I wonder if there are other TS developers who want to vote on this? 

I propose the top level comment be voted on: 

👍 for living dangerously and making the `needle` and `haystack` different types and require the `comparator` imply there is a mapping from the `needle` type to `haystack`'s type?
👎 to vote against proposed change in this issue

This is just a vote I am proposing. I will let @ironwallaby / this repos maintainers decide how to use the vote results to make a decision.

**Comment by ironwallaby** [comment] 2017-05-09 00:57
Honestly, we don't use TypeScript in any way, shape, or form, and including it was intended to be a convenience for those who do! If this is a topic that is debatable, it may be better to remove TypeScript from this repository and have somebody else maintain a fork (which we'd happily link to from the README) which can be properly maintained?

**Comment by rnemec** [comment] 2017-05-09 02:02
@darcyparker , I see your point and joyfully appreciate the "unbiased" description of living dangerously vs not. ;-)

I'd like to highlight that the .d.ts files are there to add typings to existing javascript code. And in there:
* it already supports binary finding object with value 42 in the array of objects. My change makes the .d.ts more correct in describing what the module does.
* there is no mapping function in the current method - if you would want such function, that would be different API

There should be no semantic problem saying the needle does not have to be same type as haystack. If I have a stack of products (with barcode) and want to find a particular barcode I should be able to. The comparator knows how to take a product and barcode and returns the comparison.

**Comment by darcyparker** [comment] 2017-05-09 23:28
@rnemec - Sorry about the biased 'living dangerously' in the proposed vote criteria. I still feel that way... but should let everyone decide for themselves.  There's value for both choices.

@ironwallaby - I much prefer to see the `.d.ts` in this repo. It makes life easier for typescript developers to just install one repo rather than two.  In the interest of keeping it this way and not forking the work, I'll give a thumbs up to https://github.com/darkskyapp/binary-search/pull/14.  

#14 is good if the opinion is to document the interface as it is implemented even though someone could conceivably create a bad comparator.  If more come along in the future and want to re-open this debate, then maybe we can discuss a fork.

**Comment by rnemec** [comment] 2017-05-09 23:35
@darcyparker - I got no bad feelings about the 'living dangerously'. It just reminded me, how many of us, often unintentionally, pass our opinions. And I'm a sinner there, too. :-)

**Comment by diegofrata** [comment] 2018-01-26 17:05
@darcyparker allowing different types for need and haystack is the right thing to do. It's pretty much implied that anyone using binary search is seeking to reduce the waste associated with the search. Trying to force someone to map properties or entire lists just for the sake of type safety would be to defeat the whole point of doing a binary search. 

@ironwallaby Is it possible to get this merged, please?

**Comment by ironwallaby** [comment] 2018-01-29 20:22
@diegofrata: since we don't use TypeScript here at Dark Sky (e.g. that component is community-maintained), I'm just waiting on consensus on whether or not this should be merged (or modified, or what).

**Comment by rnemec** [comment] 2018-01-29 20:29
@ironwallaby - as for community consensus: looks like everybody participating in this discussion, as well as the PR #14 is for merging.

Just saying 😉

**Comment by ironwallaby** [comment] 2018-01-29 20:33
Apologies, I had misunderstood the discussion.

**Closed by ironwallaby** 2018-01-29 20:33 UTC
